### ISSUE TITLE
Example error

### ISSUE THREAD

**Issue by jlynskey** [iamport/iamport_flutter#2]
String is not a subtype of int error occurs when running the example.
Changing amount from '38000' to 38000 and adding .tostring() after milliseconds appears to fix it.
Please confirm

**Comment by SoleeChoi** [comment]
Hello, this is Iamport Technology Team.

The data type of the `amount` property is basically integer. You can check the [`PaymentData`](https://github.com/iamport/iamport_flutter/blob/master/lib/model/payment_data.dart)  model.
That's why I added some codes to change input string to integer on the 239th line on [example/lib/screens/payment_test.yaml](https://github.com/iamport/iamport_flutter/blob/master/example/lib/screens/payment_test.dart).
So the following code would be fine.

```
PaymentData data = PaymentData.fromJson({
    ....
    'amount': int.parse('39000') or just 39000. not '39000'
});
```

The example code for the `amount` property introduced on [README.md](https://github.com/iamport/iamport_flutter/blob/master/example/README.md) was wrong. I apology for that and I will fix it on the next npm update.

Thanks.

**Comment by jlynskey** [comment]
감사합니다 :)

**Comment by SoleeChoi** [comment]
안녕하세요

이번 새 버전(v0.9.3) 업데이트에 보고주신 내용 반영하였습니다.

감사합니다.
